version: "3.9"

services:
  bot:
    image: bot:latest
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Running Bot' && \
      python main.py"
    volumes:
      - ${PWD}/app:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      fsm:
        condition: service_healthy
    networks:
      - pokerlost
    restart: always
